version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000

  postgres:
    image: postgis/postgis:12-master
    environment:
      POSTGRES_DB: purr_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sashkamihaylov.
    restart: always

  main:
    container_name: main
    build:
      context: .
    ports:
      - 5000:5000
    command: npm run start:dev
    env_file:
      - ormconfig.js
      - test.env
    depends_on:
      - postgres

volumes:
  postgres: